

init(P):-
	consult('platform.pl'), consult('DISCOVER-PLUS-REFRESHNET.pl'),                         %consult('REFRESHNET-TEST VER.pl'),
	start_tartarus(localhost,P,11),
	network(localhost,80000,80002), discover_net(10).	% CONNECTS ALL 10 NODES WITH PORTS NUMBERED 80000 TO 80010 IN LOCALHOST

% CHECK WHAT HAPPENS IF IN 80000 AND 8009 WERE TO BE SUBSTITUTED BY SOME OTHER NOS. SAY 40000 AND 40001 
% WITHOUT REFLECTING THE CORRESPONDING  CHANGE IN THE BATCH FILE
% CHECK THE netlist/1 ASSERTED AT INDIVIDUAL NODES 
% PL REPORT ANY ANOMALY IN LIST AND INFORM WHY THIS IS SO
